export const UPDATE_FILMSCREEN_PROP = 'UPDATE_FILMSCREEN_PROP';
export const LOADING_EPISODE = 'LOADING_EPISODE';
export const LOADED_EPISODE = 'LOADED_EPISODE';
export const LOADING_EPISODE_FAILED = 'LOADING_EPISODE_FAILED';
