export const UPDATE_HOMESCREEN_PROP = 'UPDATE_HOMESCREEN_PROP';
export const LOADING_FILM_LIST = 'LOADING_FILM_LIST';
export const LOADED_FILM_LIST = 'LOADED_FILM_LIST';
export const LOADING_FILM_LIST_FAILED = 'LOADING_FILM_LIST_FAILED';
